---
name: ender2pro-raspberrypi
description: |
  # Raspberry Pi Case for the Ender 2 Pro

  A simple case to mount a rasbperry pi behind the screen of an ender 2 pro
  Tested with Raspberry Pi 3B+. Should also work with Raspberry Pi 4

  Features
  - Cut outs for ribbon cable for pi camera
  - Cut outs for usb cables
  - Easy access to SD Card Camera
  - Zip Tie mounts
  

  ## Installation
  - Remove the 4 M3 screws holding on the back plate
  - Add raspberry pi with 2-4 M3x4 or M3x6 screws
  

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2022
resources:
  printer: https://www.creality.com/goods-detail/creality-ender-2-pro-3d-printer
fusion_link: https://a360.co/38oL8Z0
links:
  # Thingiverse: https://www.thingiverse.com/thing:xxxx
  Printables: https://www.printables.com/model/161098-ender-2-pro-raspberry-pi-case
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  # Github: https://github.com/foo
  # Blog: https://foo.com
